name: CI
on: push
jobs:
  vint:
    name: Lint with Vint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Lint with Vint
        run: |
          python -m pip install vim-vint
          vint .
  vimlint:
    name: Lint with vimlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint with vimlint
        run: |
          git clone https://github.com/syngan/vim-vimlint $HOME/vim-vimlint
          git clone https://github.com/vim-jp/vim-vimlparser $HOME/vim-vimlparser
          $HOME/vim-vimlint/bin/vimlint.sh -u -l $HOME/vim-vimlint -p $HOME/vim-vimlparser .
